spring:
  redis:
    #    默认配置
    host: kamo-cloud-interior-test.kamowl.com
    port: 6379
    password: 123456
    timeout: 6000
    database: 3
#    lettuce:
#      pool:
#        max-active: 20
#        max-wait: -1
#        max-idle: 10
#        min-idle: 0
    #    自定义配置
#    local:
#      host: 127.0.0.1
#      port: 6379
#      password: admin